import { Nullable } from '~/utils/typeUtils'

export type Environment = 'development' | 'production'

export type Env = {
  AAO_ENDPOINT: string
  AMPLITUDE_API_KEY: Nullable<string>
  AMPLITUDE_PROXY: Nullable<string>
  API_URL: string
  APP_NAME: string
  API_KEY: string
  ARCHIVE_ENDPOINT: string
  AUDIUS_NETWORK_CHAIN_ID: number
  AUDIUS_URL: string
  BITSKI_CALLBACK_URL: string
  BITSKI_CLIENT_ID: string
  CACHE_PRUNE_MIN: string
  CLAIM_DISTRIBUTION_CONTRACT_ADDRESS: Nullable<string>
  CLAIMABLE_TOKEN_PDA: string
  CLAIMABLE_TOKEN_PROGRAM_ADDRESS: string
  COGNITO_KEY: Nullable<string>
  COGNITO_TEMPLATE_ID: Nullable<string>
  ENTITY_MANAGER_ADDRESS: string
  ENVIRONMENT: Environment
  ETH_BRIDGE_ADDRESS: Nullable<string>
  ETH_NETWORK_ID: string
  ETH_OWNER_WALLET: Nullable<string>
  ETH_PROVIDER_URL: string
  ETH_REGISTRY_ADDRESS: string
  ETH_TOKEN_ADDRESS: string
  ETH_TOKEN_BRIDGE_ADDRESS: Nullable<string>
  EXPLORE_CONTENT_URL: string
  FCM_PUSH_PUBLIC_KEY: Nullable<string>
  FINGERPRINT_ENDPOINT: Nullable<string>
  FINGERPRINT_PUBLIC_API_KEY: Nullable<string>
  GA_HOSTNAME: string
  GA_MEASUREMENT_ID: string
  HCAPTCHA_BASE_URL: string
  HCAPTCHA_SITE_KEY: string
  IDENTITY_SERVICE: string
  INSTAGRAM_APP_ID: string
  INSTAGRAM_REDIRECT_URL: string
  LOOKUP_TABLE_ADDRESS: string
  OPTIMIZELY_KEY: string
  STAKING_BRIDGE_PROGRAM_ID: string
  PUBLIC_HOSTNAME: string
  PUBLIC_PROTOCOL: string
  BASENAME: string
  REACHABILITY_URL: string
  RECAPTCHA_SITE_KEY: string
  REGISTRY_ADDRESS: string
  SAFARI_WEB_PUSH_ID: string
  SCHEME: string
  SENTRY_DSN: string
  SOL_BRIDGE_ADDRESS: Nullable<string>
  SOL_TOKEN_BRIDGE_ADDRESS: Nullable<string>
  SOLANA_CLUSTER_ENDPOINT: string
  SOLANA_FEE_PAYER_ADDRESS: string
  SOLANA_RELAY_ENDPOINT: string
  SOLANA_TOKEN_PROGRAM_ADDRESS: string
  SOLANA_WEB3_CLUSTER: string
  SUGGESTED_FOLLOW_HANDLES: string
  TIKTOK_APP_ID: string
  USE_HASH_ROUTING: boolean
  WAUDIO_MINT_ADDRESS: string
  WORMHOLE_ADDRESS: Nullable<string>
  WORMHOLE_RPC_HOSTS: Nullable<string>
  EMAIL_ENCRYPTION_UUID?: number
  EMAIL_ENCRYPTION_PUBLIC_KEY?: string
  DISCORD_BOT_SERVER?: string
}
